name: pkbr
channels:
 - https://conda.anaconda.org/rdkit
dependencies:
  - python>=3.7,<3.8
  - pip>=19.1,<20.3
  - pip:
    - -r file:requirements.txt
    # development
    - -e .
    # analysis
    - jupyter
    - seaborn
